### ISSUE TITLE
POINTER TO ARRAY [untagged] accepted as the tagged ARRAY

### ISSUE THREAD

**Issue by Oleg-N-Cher** [Oleg-N-Cher/CPfront#11]
SovietPony reports:
```
MODULE Test;
  IMPORT SYSTEM;

  VAR
    s: POINTER TO ARRAY [untagged] OF SHORTCHAR;

  PROCEDURE Call (IN s: ARRAY OF SHORTCHAR);
  END Call;

BEGIN
  Call(s)
END Test.
```

**Comment by Oleg-N-Cher** [comment]
It would be best to correct this error at the level of the frontend. In BlackBox, this check is performed at the back-end level in the procedures Index & VarParDynArr of the module DevCPC486. If that check was done in front-end, the error would not appear in CPfront.

I propose such a correction.

![image](https://user-images.githubusercontent.com/1090608/58517187-3764e900-81b3-11e9-893c-bb1078c5ab24.png)

**Comment by Oleg-N-Cher** [comment]
https://community.blackboxframework.org/viewtopic.php?f=48&t=225

**Comment by Oleg-N-Cher** [comment]
The type description takes into account the tagging of a pointer, not the base type:

```
TYPE
	T1 = POINTER TO ARRAY [untagged] OF SHORTCHAR;
	T2 = POINTER [untagged] TO ARRAY OF SHORTCHAR;
	T3 = POINTER TO ARRAY OF SHORTCHAR;
	T4 = POINTER [untagged] TO ARRAY [untagged] OF SHORTCHAR;
```
Wrong:
```
typedef
	SHORTCHAR *Test_T1;

typedef
	SHORTCHAR *Test_T2;

typedef
	struct SHORTCHAR_ARRAY *Test_T3;

typedef
	SHORTCHAR *Test_T4;
```

Correct:
```
typedef
	SHORTCHAR *Test_T1;

typedef
	struct SHORTCHAR_ARRAY *Test_T2;

typedef
	struct SHORTCHAR_ARRAY *Test_T3;

typedef
	SHORTCHAR *Test_T4;
```

**Comment by luowy** [comment]
Hi, Oleg

you may check my patch(some time ago);

	PROCEDURE DynArrParCheck (ftyp: DevCPT.Struct; VAR ap: DevCPT.Node; fvarpar: BOOLEAN);
	(* check array compatibility *)
		VAR atyp: DevCPT.Struct;
	BEGIN (* ftyp.comp = DynArr *)
		atyp := ap.typ; 
		IF atyp.form IN {Char8, Char16, String8, String16} THEN
			IF ~fvarpar & (ftyp.baseTyp.form = Char16) & (atyp.form = String8) THEN Convert(ap, DevCPT.string16typ)
			ELSE CheckString(ap, ftyp, 67);
			END
		ELSE		
			WHILE (ftyp.comp = DynArr) & ((atyp.comp IN {Array}) OR (atyp.form IN {String8, String16})
					OR (atyp.comp = DynArr)&((ftyp.sysflag = atyp.sysflag)OR(atyp.sysflag = 0)) 
					) DO
				ftyp := ftyp.baseTyp; atyp := atyp.baseTyp
			END; 
			IF ftyp.comp = DynArr THEN
				IF (ftyp.sysflag # atyp.sysflag)&(atyp.sysflag # 0) THEN err(115);
				ELSE err(67)
				END; 
			ELSIF ~fvarpar & (ftyp.form = Pointer) & DevCPT.Extends(atyp, ftyp) THEN (* ok *)
			ELSIF ~DevCPT.EqualType(ftyp, atyp) THEN err(66)
			END
		END
	END DynArrParCheck;

**Comment by Oleg-N-Cher** [comment]
Very nice patch, Wening Luo! I tested it, and it works fine.

Since the module DevCPB is not included in CPfront, I can't use your patch directly, so I have to make a fix in back-end too, as in BlackBox now. In this case, BlackBox can be a host system for CPfront with your patch, and without it. Everything will work. I am truly grateful to you for your help.

**Comment by Oleg-N-Cher** [comment]
My back-end solution in CPV.ActualPar:

![image](https://user-images.githubusercontent.com/1090608/58598519-6c417080-8285-11e9-86c8-3f9e3c729a29.png)
